---
trust-domain: "ap"
task-priority: low

taskgraph:
  cached-task-prefix: "ap.v2.tc-slackord"
  repositories:
    tc_slackord:
      name: "tc-slackord"

  register: eije_taskgraph:register

workers:
  aliases: {}
